# .streamlit/secrets.toml
[Mathematic]
password = "611933"

[Science]
password = "933611"

[MoralEdu]
password = "720144"

[Social]
password = "144721"

['English Language']
password = "933144"

['Arabic Arab']
password = "144933"

['Arabic (Non-A)']
password = "611144"



